#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JenaSENSE.Resource", IsApplication=true)]

namespace JenaSENSE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::WebView.Plugin.Droid.Resource.String.ApplicationName = global::JenaSENSE.Resource.String.ApplicationName;
			global::WebView.Plugin.Droid.Resource.String.Hello = global::JenaSENSE.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int LocalWebView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int buttonAPI = 2131034113;
			
			// aapt resource value: 0x7f05002a
			public const int buttonWeb = 2131034154;
			
			// aapt resource value: 0x7f050002
			public const int firstBlock = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int firstBlockLabel = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int secondBlock = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int secondBlockLabel = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int totalAgeLabel = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int totalAgeReturn = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int totalAgeSection = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int totalAngerLabel = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int totalAngerReturn = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int totalAngerSection = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int totalContemptLabel = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int totalContemptReturn = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int totalContemptSection = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int totalCountLabel = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int totalCountReturn = 2131034118;
			
			// aapt resource value: 0x7f050019
			public const int totalDisgustLabel = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int totalDisgustReturn = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int totalDisgustSection = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int totalFearLabel = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int totalFearReturn = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int totalFearSection = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int totalHappinessLabel = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int totalHappinessReturn = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int totalHappinessSection = 2131034142;
			
			// aapt resource value: 0x7f050008
			public const int totalManLabel = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int totalManReturn = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int totalManSection = 2131034119;
			
			// aapt resource value: 0x7f050022
			public const int totalNeutralLabel = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int totalNeutralReturn = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int totalNeutralSection = 2131034145;
			
			// aapt resource value: 0x7f050025
			public const int totalSadnessLabel = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int totalSadnessReturn = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int totalSadnessSection = 2131034148;
			
			// aapt resource value: 0x7f050004
			public const int totalSection = 2131034116;
			
			// aapt resource value: 0x7f050028
			public const int totalSurpriseLabel = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int totalSurpriseReturn = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int totalSurpriseSection = 2131034151;
			
			// aapt resource value: 0x7f05000b
			public const int totalWomanLabel = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int totalWomanReturn = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int totalWomanSection = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoadFromWeb = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
